### ISSUE TITLE
The box you're attempting to add doesn't support the provider you requested.

### ISSUE THREAD

**Issue by rocLv** [rails/rails-dev-box#109]
When I try to run `vagrant up`, I got messages as follow:
```terminal
Bringing machine 'default' up with 'aws' provider...
==> default: HandleBoxUrl middleware is deprecated. Use HandleBox instead.
==> default: This is a bug with the provider. Please contact the creator
==> default: of the provider you use to fix this.
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    default: Box Provider: aws
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/trusty64'
    default: URL: https://vagrantcloud.com/ubuntu/trusty64
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

Name: ubuntu/trusty64
Address: https://vagrantcloud.com/ubuntu/trusty64
Requested provider: [:aws]
```
Should I have a aws account?

**Comment by fxn** [comment]
No idea, the box runs with VirtualBox, there are [other providers](http://docs.vagrantup.com/v2/getting-started/providers.html), but you need to do something extra to request any of them.

**Comment by rocLv** [comment]
I think it's network problem. We have GFW.
So close this issue.

**Comment by yuqiangit** [comment]
vagrant up --provider virtualbox

try this cmd.

**Comment by raygervais** [comment]
Thank you @yuqiangit, it enabled me to at least download the VM on Fedora 25.

**Comment by justincletus** [comment]
@yuqiangit  vagrant up --provider virtualbox is working for me. thank you

**Comment by kmadisa** [comment]
https://github.com/rails/rails-dev-box/issues/109#issuecomment-286354794 `vagrant up --provider virtualbox` worked for me and also got the following message:

```
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.

```

**Comment by pdelteil** [comment]
> vagrant up --provider virtualbox
> 
> try this cmd.

Solved my problem.

**Comment by anibalardid** [comment]
> [#109 (comment)](https://github.com/rails/rails-dev-box/issues/109#issuecomment-286354794) `vagrant up --provider virtualbox` worked for me and also got the following message:
> 
> ```
> The provider 'virtualbox' that was requested to back the machine
> 'default' is reporting that it isn't usable on this system. The
> reason is shown below:
> 
> Vagrant has detected that you have a version of VirtualBox installed
> that is not supported by this version of Vagrant. Please install one of
> the supported versions listed below to use Vagrant:
> 
> 4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2
> 
> A Vagrant update may also be available that adds support for the version
> you specified. Please check www.vagrantup.com/downloads.html to download
> the latest version.
> ```

try with:
vagrant box add hashicorp/precise64

**Comment by AAber** [comment]
For me:

``sudo dpkg -i vagrant_2.2.6_x86_64.deb``

fixed the problem

**Comment by Ludloops** [comment]
> vagrant up --provider virtualbox
> 
> try this cmd.


This comment did the trick thanks  @yuqiangit
