### ISSUE TITLE
no rails found

### ISSUE THREAD

**Issue by pratamawijaya** [rails/rails-dev-box#111]
I have clone these repo, and then vagrant up my repo, after all complete, im trying vagrant ssh then running 'rails' command, but its not installed..

**Comment by fxn** [comment]
Yes, it is not installed because the normal use case is that someone wants to clone *their* fork (to create a pull request from it), and the dev box knows nothing about it.

Please have a look at the [recommended workflow](https://github.com/rails/rails-dev-box#recommended-workflow).
