### ISSUE TITLE
Public directory uploads getting over written solution?

### ISSUE THREAD

**Issue by slavajacobson** [rails/rails-dev-box#113]
When using paperclip to upload an image, it puts it in public/system directory, but as soon as I make a change and save a file via Host, rsync kicks in and the public/system gets deleted.

Any suggestions on how to prevent this from happening?

**Comment by fxn** [comment]
This repository provides a virtual machine for Rails core development, not Rails application development, though some people take it as a starting VM.

Nevertheless, questions or isses which are specific to Vagrant would be better solved in Vagrant channels. You could maybe try [here](http://stackoverflow.com/questions/tagged/vagrant) for example.
