### ISSUE TITLE
bundle fails when installing nokogiri 1.6.7.2 with native extensions

### ISSUE THREAD

**Issue by hmspider** [rails/rails-dev-box#117]
Workaround: 
`vagrant@rails-dev-box:/vagrant/rails$ bundle config build.nokogiri --use-system-libraries --with-xml2-include=/usr/include/libxml2/`

**Comment by fxn** [comment]
Looks like a duplicate of #116.

Could you please update this project by pulling and reboot the dev box to get more RAM in the guest?
