### ISSUE TITLE
Dev box on centos 7

### ISSUE THREAD

**Issue by lebogan** [rails/rails-dev-box#120]
Is it possible to build this to run on centos 7 with the same shared folder philosoiphy?

**Comment by fxn** [comment]
I have never done it, but if you mean that the host machine runs CentOS, as far as I know, it should work just fine.

**Comment by lebogan** [comment]
Thanks for  the reply. Apologies if I wasn't very clear. I want the
guest to run CentOS from my Fedora host.
Lewis
On Sun, 2016-09-18 at 23:15 -0700, Xavier Noria wrote:
> > I have never done it, but if you mean that the host machine runs
CentOS, as far as I know, it should work just fine.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/rails/rai
ls-dev-box","title":"rails/rails-dev-box","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/ass
ets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/rails/rails-dev-
box"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fxn in
#120: I have never done it, but if you mean that the host machine
runs CentOS, as far as I know, it should work just
fine."}],"action":{"name":"View
Issue","url":"https://github.com/rails/rails-dev-
box/issues/120#issuecomment-247917499"}}}

**Comment by fxn** [comment]
In theory that can be done, but this repo won't work as is. It would be trivial to change the base image, but the guest is provisioned using `apt-get`. See [_bootstrap.sh_](https://github.com/rails/rails-dev-box/blob/master/bootstrap.sh).

You could take this project as a model, though, and replicate the same idea for CentOS. Shared folders are a feature of VirtualBox, does not depend on the guest as long as it is supported.

**Comment by lebogan** [comment]
Thanks, I'll close this and give it a shot.

**Comment by fxn** [comment]
Let me comment this project is fine as is and does not want to support other guest OS. 

Surely you want to give it a shot for personal use (in which case go for it!), but let me just clarify this, wouldn't like that you work on a patch that would not be accepted.
