### ISSUE TITLE
vagrant up fails on macosx

### ISSUE THREAD

**Issue by mattlindsey** [rails/rails-dev-box#124]
I'm getting the error below:

mattlindsey@MATTs-MBP rails-dev-box (master) $ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/yakkety64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'ubuntu/yakkety64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/yakkety64"]
Error:

**Comment by mattlindsey** [comment]
Solution: http://stackoverflow.com/questions/35519389/vagrant-cannot-find-box

**Comment by fxn** [comment]
Awesome, appreciate the followup.
