### ISSUE TITLE
Rails 5?

### ISSUE THREAD

**Issue by AaronCowan** [rails/rails-dev-box#128]
I'm looking to hack on the latest rails release using this box, but it looks like it's using rails 4.2.7.1. Is there something I'm missing? 

```
ubuntu@rails-dev-box:~$ rails -v
Rails 4.2.7.1
```

I've gone into `/vagrant/rails` and run `gem build rails.gemspec`, but when I run `gem install ./rails-5.1.0.alpha.gem` I get 
```
ubuntu@rails-dev-box:/vagrant/rails$ gem install ./rails-5.1.0.alpha.gem 
ERROR:  Could not find a valid gem 'railties' (= 5.1.0.alpha) in any repository
ERROR:  Possible alternatives: railties
```
EDIT: 

Nevermind it's in the docs http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html

`$ bundle exec rails new ~/my-test-app --dev`

this can be closed.

**Comment by fxn** [comment]
Would not be a good idea to duplicate instructions, but [I have added a pointer to the guide](https://github.com/rails/rails-dev-box/commit/f449a512cdb56b2877cb268fe40b7491a06ff9fa) to remind people there are tips there.
