### ISSUE TITLE
Windows 7 not working 'vargant up' because of 0.0.0.0

### ISSUE THREAD

**Issue by vadimeremeev** [rails/rails-dev-box#135]
Have to modify line to specify config.vm.network as per below: 

`config.vm.network :forwarded_port, guest: 3000, host: 3000, host_ip: "127.0.0.1"`

**Comment by fxn** [comment]
Why do you by not working? Does `vagrant up` fail to boot the VM? If so, which is the error?

**Comment by vadimeremeev** [comment]
Yes, `vagrant up` fail to boot the VM with the error: 

```
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/is_port_o
pen.rb:21:in `initialize': The requested address is not valid in its context. -
connect(2) for "0.0.0.0" port 9000 (Errno::EADDRNOTAVAIL)
```

After I modified the config line as in my first post it works.

**Comment by yahonda** [comment]
It is likely duplicated with https://github.com/hashicorp/vagrant/issues/8395 and fixed by https://github.com/hashicorp/vagrant/pull/8399 ,that fix has been available since Vagrant 1.9.4.

The latest version of Vagrant is 2.0.1.

**Comment by sobrinho** [comment]
@fxn this can be closed 👍

**Comment by fxn** [comment]
Thanks!
