### ISSUE TITLE
Using this box for rails application?

### ISSUE THREAD

**Issue by edcu11** [rails/rails-dev-box#136]
I was wondering if I would be able to use this box to develop applications? Do I follow the same rails installation process I would follow elsewhere or is there any problem with it?

**Comment by fxn** [comment]
This VM is designed for Rails core development. In practice that means that [provisioning](https://github.com/rails/rails-dev-box/blob/master/bootstrap.sh) installs all you need to contribute a patch being able to run the suite in particular, and also it means that by desing you install nothing else.

This is a Linux VM, so you can modify the provisioning script, or you can delete packages, databases, ..., but that is really up to you.

There are some VMs thought for application development like [this one](https://github.com/amaia/rails-starter-box).
