### ISSUE TITLE
Git Error: Could not parse object on Bundle command

### ISSUE THREAD

**Issue by Rahul-Sagore** [rails/rails-dev-box#139]
Hi,

I was setting up rails repo using vagrant. I was running `bundle` command inside `/vagrant/rails/`.
Then this is the error I got:
```
fatal: Could not parse object '7e3c714a09ae2b38d2620835e794150d8857cd49'.
Git error: command `git reset --hard 7e3c714a09ae2b38d2620835e794150d8857cd49` in directory /home/ubuntu/.bundle/ruby/2.4.0/rb-inotify-7e3c714a09ae has failed.
```
<img width="1254" alt="screen shot 2017-06-18 at 12 53 23 am" src="https://user-images.githubusercontent.com/3587851/27255669-e1dbe8ac-53c0-11e7-9c4c-37705fe3be04.png">

Additional Info:
System:      Mac OS X El captain 10.11.2
Vagrant:      1.9.1
VirtualBox: 5.1.12 r112440

**Comment by fxn** [comment]
I created a new VM and with an up to date `master` branch `bundle install` inside _vagrant/rails_ succeeded.

I am going to close on the assumption that your session founded some kind of Git hiccup unrelated to the dev box itself.
