### ISSUE TITLE
what's is the password for the user "ubuntu"? I just can't login with command "vagrant ssh"

### ISSUE THREAD

**Issue by darenme** [rails/rails-dev-box#140]
![default](https://user-images.githubusercontent.com/18227489/30769555-d30e8c4c-a04d-11e7-8c17-9b572802f159.png)
I want to change the defalut "login" dir, so changed the /etc/passwd file, after that "vagrant ssh" ask for the password. and why my username is "ubuntu", not "vagrant" like others?

**Comment by darenme** [comment]
**# I just found the password, it's in the ".....\.vagrant.d\boxes\ubuntu-VAGRANTSLASH-zesty64\20170922.0.0\virtualbox\Vagrantfile". but I don't konw how to close or delete this issue.**

**Comment by fxn** [comment]
I'll do it, thanks anyway.
