### ISSUE TITLE
[question] Is there a reason the dev box is not docker based?

### ISSUE THREAD

**Issue by kinnrot** [rails/rails-dev-box#143]

**Comment by fxn** [comment]
I started working on it a while back, had a partial setup and reserved the rails namespace. And then I saw the partial work, compared with the trivial shell script that provisions this VM and how trivial is to think in the VM as a self-contained and persistent machine, and lost interest.

AFAIK no one else in the team is working on that either.

**Comment by tiendo1011** [comment]
@fxn Do you think it's good idea if I give it a try?
