### ISSUE TITLE
missing autoreconf libraries 

### ISSUE THREAD

**Issue by niko-pax-uofa** [rails/rails-dev-box#153]
I couldn't get bundle install to work, but the following fixed it for me:
`sudo apt-get install autoconf  dh-autoreconf`

The gem that failed to build was: ffi (1.9.21)

>  Installing ffi 1.9.21 with native extensions
> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
> 
>     current directory: /tmp/bundler20180509-19637-16775j3ffi-1.9.21/gems/ffi-1.9.21/ext/ffi_c
> /usr/bin/ruby2.5 -r ./siteconf20180509-19637-1ljzgd7.rb extconf.rb
> checking for ffi.h... no
> checking for ffi.h in /usr/local/include,/usr/include/ffi... no
> checking for shlwapi.h... no
> checking for rb_thread_blocking_region()... no
> checking for rb_thread_call_with_gvl()... yes
> checking for rb_thread_call_without_gvl()... yes
> creating extconf.h
> creating Makefile
> 
> current directory: /tmp/bundler20180509-19637-16775j3ffi-1.9.21/gems/ffi-1.9.21/ext/ffi_c
> make "DESTDIR=" clean
> 
> current directory: /tmp/bundler20180509-19637-16775j3ffi-1.9.21/gems/ffi-1.9.21/ext/ffi_c
> make "DESTDIR="
> Running autoreconf for libffi
> /tmp/bundler20180509-19637-16775j3ffi-1.9.21/gems/ffi-1.9.21/ext/ffi_c/libffi/autogen.sh: 2: exec: autoreconf: not found
> libffi.mk:6: recipe for target '"/tmp/bundler20180509-19637-16775j3ffi-1.9.21/gems/ffi-1.9.21/ext/ffi_c/libffi-x86_64-linux-gnu"/.libs/libffi_convenience.a' failed
> make: *** ["/tmp/bundler20180509-19637-16775j3ffi-1.9.21/gems/ffi-1.9.21/ext/ffi_c/libffi-x86_64-linux-gnu"/.libs/libffi_convenience.a] Error 127
> 
> make failed, exit code 2
> 
> Gem files will remain installed in /tmp/bundler20180509-19637-16775j3ffi-1.9.21/gems/ffi-1.9.21 for inspection.
> Results logged to /tmp/bundler20180509-19637-16775j3ffi-1.9.21/extensions/x86_64-linux/2.5.0/ffi-1.9.21/gem_make.out
> 
> An error occurred while installing ffi (1.9.21), and Bundler cannot continue.
> Make sure that `gem install ffi -v '1.9.21'` succeeds before bundling.
> 
> In Gemfile:
>   blade-sauce_labs_plugin was resolved to 0.7.2, which depends on
>     selenium-webdriver was resolved to 3.5.1, which depends on
>       childprocess was resolved to 0.7.1, which depends on
>         ffi

**Comment by fxn** [comment]
This was fixed in https://github.com/rails/rails-dev-box/commit/7cb1f29fcb21bd54460385c890097e38f28d52fb. Could you please pull and try again?

**Comment by niko-pax-uofa** [comment]
Yes you are right, i must have pulled after doing "vagrant up".
