### ISSUE TITLE
Ubuntu 19.04 (disco64) not available

### ISSUE THREAD

**Issue by anujmiddha** [rails/rails-dev-box#173]
As Ubuntu version 19.04 has reached end of life on Jan 23rd 2020, it is not available anymore on cloud-images.ubuntu.com . With the default Vagrantfile, running `vagrant up` results in a `404 Not Found` error. Perhaps we can update it to 19.10 (Eoan) or 20.04 (Focal)?

**Comment by fxn** [comment]
Done in https://github.com/rails/rails-dev-box/commit/4d87263a16cb70a8883dbe3446be60dcdc870116.

`vagrant up` still hangs on "SSH auth method: private key", needed a few tries before I could boot the VM and check things looked good.

**Comment by anujmiddha** [comment]
Thanks @fxn . The timeout issue you are facing is probably due to the VM taking longer than 5 mins (default timeout for vagrant) to boot up. I've created a PR increasing this timeout to 10 mins. Please take a look.

https://github.com/rails/rails-dev-box/pull/174
