### ISSUE TITLE
SSD with ext4 partition with Ubuntu 22.10 Not Recognized in BIOS but only in Ubuntu/Windows

### ISSUE THREAD

**Issue by MichielP80** [rails/rails-dev-box#207]
After trying to reinstall of my laptop to Ubuntu 23.04, the BIOS do not recognize my SSD with an ext4 partition with Ubuntu 22.10 on it.
I have tryed with the Ubuntu Live USB to delete and format the partitions, but it doesn´t matter.
Proberly their was something wrong with a permission or mounting error?

I have try it with 2 SSD harddisk, wich i connected to my USB port.

-Samsung 840EVO (model MZ - 7TE500
-Samsung 850 PRO 9model MZ-7KE256 (maybe to old? 2016)

After buying a new SSD the BIOS saw the disk and i was be able to install Ubuntu 22.10 LTS and also start up with the installation of 23.04)

**Comment by yahonda** [comment]
Hi, This issue does not look like related to rails-dev-box, that is a virtual box using Vagrant.
