### ISSUE TITLE
PG::ConnectionBad

### ISSUE THREAD

**Issue by hopewise** [rails/rails-dev-box#88]
When I do rake db:migrate, I get error, I am setting my database as:

development:
  adapter: postgresql
  encoding: unicode
  database: postgres
  host: localhost
  pool: 5
  username: vagrant
  password:

the error is:

rake aborted!
PG::ConnectionBad: fe_sendauth: no password supplied
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `initialize'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `new'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `connect'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:568:in `initialize'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_handling.rb:87:in `connection'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:909:in `initialize'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:807:in `new'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:807:in `up'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:785:in `migrate'
/var/lib/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by fxn** [comment]
Hey, did you figure this out?

**Comment by hopewise** [comment]
No, I just decided to forget virtual solutions and move to a real
environment, I've burned lots of hours..




On Tue, Feb 3, 2015 at 7:07 PM, Xavier Noria <notifications@github.com>
wrote:

> Hey, did you figure this out?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails/rails-dev-box/issues/88#issuecomment-72690349>.
>



-- 
--
Kind Regards,
---------------------------------------------
Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East

**Comment by fxn** [comment]
I generated an application with `--database=postgresql` inside the virtual machine, generated a scaffold, and used the application running in the guest in development mode from the host. It had normal speed.

Closing this ticket then because cannot see any significant slow down.

**Comment by nielsenrechia** [comment]
HI i have the same problem with postgres here.

when i run
rake db:create

got this problem
fe_sendauth: no password supplied
/var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'

with the database like this

defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: vagrant
  password:
  host: localhost

development:
  database: knn_development
  <<: *defaults

test:
  database: knn_test
  <<: *defaults

production:
  database: knn_production
  <<: *defaults

someone can help me?
thanks
