### ISSUE TITLE
Readme needs additional explanation for port-forwarding

### ISSUE THREAD

**Issue by maxArturo** [rails/rails-dev-box#89]
I loaded up the rails box with Vagrant and upon creating a test app was stumped because I couldn't forward the port. Running curl on guest with `'http://localhost:3000'` yielded results, but not on the host side. Following all the vagrant docs still didn't lead me anywhere, until I ran into [this SO post](https://stackoverflow.com/questions/5984217/vagrants-port-forwarding-not-working/5999945#5999945) that suggested to bind WEBrick to `0.0.0.0`, instead of `127.0.0.1` so that all interfaces can access it. 

I would be surprised if not more would-be collaborators would run into issues there, so its likely worthwhile to include in the docs. I'd love to hear if anyone else has run into that. 

Thanks!

**Comment by czak** [comment]
I believe this has been solved in #90 and can now be closed. @maxArturo can you confirm?

**Comment by maxArturo** [comment]
Confirmed - @fxn edited and pulled the readme edit for clarification.

**Comment by fxn** [comment]
:+1:
