### ISSUE TITLE
Install ruby 2.2.1

### ISSUE THREAD

**Issue by jvanbaarsen** [rails/rails-dev-box#95]
Since Railties needs to have ruby 2.2.1, I think it would be good to have that installed when running `vagrant up`

**Comment by fxn** [comment]
You're right. Brightbox has not still packaged 2.2.1, but I am sure they will soon. It's an exceptional situation that we need the very last thing to run, let's do nothing by now and wait a little bit for the packages.

**Comment by jvanbaarsen** [comment]
Ok. Ill close this one for Now.
