### ISSUE TITLE
Use rbenv for ruby version management

### ISSUE THREAD

**Issue by jvanbaarsen** [rails/rails-dev-box#96]
@fxn What do you think about using rbenv for ruby version management? Since you might want to test rails against an older version of ruby then that is installed on the dev-box.

At this moment you have to build that version from source and manage the versions manually. I know there has been a discussion about this back in 2013, at that time rvm was decided as a ruby version manager. Since we are 2 years further in the future, I want to bring this up again.

If you're interested in this change I'll be willing to create this.

**Comment by fxn** [comment]
The reason we use a package, and the reason the dev box used RVM for a while, is that the use case I want to optimize for is the occasional person that wants to fire up an environment and work on some patch.

For that use case, I prefer to install binaries and cut on the time needed to compile sources. RVM offered binaries but in the end Brightbox packages were the easiest solution.

Then, if someone wants more from this environment, then they can customize it. In particular, installing rbenv or RVM is easy for someone with the profile of who is going to patch Rails.

**Comment by jvanbaarsen** [comment]
Ok, thanks for explaining :heart:
