### ISSUE TITLE
How to fix `mri_22` is not a valid platform.

### ISSUE THREAD

**Issue by sergey-alekseev** [rails/rails-dev-box#98]
I haven't been using rails-dev-box for a while. When I've recently logged in with `vagrant ssh` and tried to `bundle` I got the following error:
```
vagrant@rails-dev-box:/vagrant/rails$ bundle
`mri_22` is not a valid platform. The available options are: [:ruby, :ruby_18, :ruby_19, :ruby_20,
:ruby_21, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :rbx, :jruby, :jruby_18, :jruby_19, :mswin, :mingw,
:mingw_18, :mingw_19, :mingw_20, :mingw_21, :x64_mingw, :x64_mingw_20, :x64_mingw_21]
```

This is caused by the recent upgrade of Rails to [Ruby 2.2](https://github.com/rails/rails-dev-box/pull/91) (and then to [Ruby 2.2.1](https://github.com/rails/rails-dev-box/issues/97)).

I fixed this error by running `sudo gem update bundler` inside the virtual machine.

**Comment by sergey-alekseev** [comment]
I created the issue to help other developers who encounter this error. Hope they will find the issue in Google.

**Comment by fxn** [comment]
Good!
